# Generated by Django 3.1.7 on 2021-08-25 16:02

import app.models
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datein', models.DateField()),
                ('dateout', models.DateField()),
                ('state', models.CharField(choices=[(app.models.State['av'], 'Available'), (app.models.State['re'], 'Requested'), (app.models.State['de'], 'Deleted')], default=app.models.State['av'], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stay_Data_Con',
            fields=[
                ('stayid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.stay')),
                ('conn', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='stay',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.CreateModel(
            name='Stay_Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptid', models.UUIDField()),
                ('stayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stay')),
            ],
            options={
                'unique_together': {('stayid', 'receiptid')},
            },
        ),
        migrations.AddConstraint(
            model_name='stay',
            constraint=models.UniqueConstraint(fields=('email', 'datein', 'dateout'), name='unique_stay'),
        ),
    ]
