# Generated by Django 3.1.7 on 2021-05-17 17:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stay_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datein', models.DateField()),
                ('dateout', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt_Data',
            fields=[
                ('id_receipt', models.UUIDField(default=uuid.uuid4)),
                ('stay_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.stay_data')),
            ],
        ),
        migrations.AddField(
            model_name='stay_data',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices', models.JSONField()),
                ('stay_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.stay_data')),
            ],
        ),
        migrations.CreateModel(
            name='Policy_Consent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent', models.BooleanField()),
                ('policy_id', models.CharField(max_length=100)),
                ('timestamp', models.DateField()),
                ('stay_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.stay_data')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stay_data',
            constraint=models.UniqueConstraint(fields=('email', 'datein', 'dateout'), name='unique_stay'),
        ),
        migrations.AddConstraint(
            model_name='receipt_data',
            constraint=models.UniqueConstraint(fields=('id_receipt', 'stay_id'), name='unique_receipt'),
        ),
    ]
