# Generated by Django 3.1.7 on 2021-08-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datein', models.DateField()),
                ('dateout', models.DateField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Stay_Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptid', models.UUIDField()),
                ('stayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stay')),
            ],
            options={
                'unique_together': {('stayid', 'receiptid')},
            },
        ),
        migrations.AddConstraint(
            model_name='stay',
            constraint=models.UniqueConstraint(fields=('email', 'datein', 'dateout'), name='unique_stay'),
        ),
    ]
