# Generated by Django 3.1.7 on 2021-04-26 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt_data',
            name='receipt_timestamp',
        ),
        migrations.AlterField(
            model_name='receipt_data',
            name='id_receipt',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
