# Generated by Django 3.1.7 on 2021-08-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
