# Generated by Django 3.1.7 on 2021-04-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210426_1651'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='receipt_data',
            constraint=models.UniqueConstraint(fields=('id_receipt', 'stay_id'), name='unique_receipt'),
        ),
    ]
