# Generated by Django 3.1.7 on 2021-04-27 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210427_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt_data',
            name='id_receipt',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
